---
- name: Manage Arista EOS EVPN/VXLAN Configuration
  hosts: DC1_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  vars:
    fabric_dir_name: "{{fabric_name}}"
    execute_tasks: false
  tasks:

    - name: deploy configuration to device
      tags: [deploy]
      import_role:
         name: arista.avd.eos_config_deploy_eapi