---
# Validation lab
# local users
local_users:
  arista:
    privilege: 15
    role: network-admin
    sha512_password: "$6$NZbqb9T.KM9Y9OIt$63BRX5bMHOroTNv4nA.fdG858fl39XDAbJo1Ac8ekfodqVEhD74CXa2R.KOKw80ROYGIEAihEi3Zehx/m228d/"
  
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1"

  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj."

  ansible:
    privilege: 15
    role: network-admin
    sha512_password: "$6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/"

# Cloud Vision server information
# cvp_instance_ips: 
#   - 10.155.0.1
# cvp_ingestauth_key: ''
# cvp_ingestauth_key: telarista


# # Management interface configuration | Required
# mgmt_vrf_routing: < boolean | default -> false >
# mgmt_interface: < mgmt_interface | default -> Management1 >
mgmt_interface: Management0
# mgmt_interface_vrf: < vrf_name | default -> MGMT >
mgmt_interface_vrf: mgmt
# OOB Management network default gateway.
mgmt_gateway: 172.17.0.1

# dns servers.
name_servers:
  - 192.168.2.1
  - 8.8.8.8

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
ntp_servers:
 - 192.168.0.2
 - 192.168.0.3
