---
# Endpoint connectivity in the online Docs

port_profiles:
  Hosts1:
    mode: trunk
    vlans: "10,12"
  Hosts2:
    mode: trunk
    vlans: "10,34"
  Old_Gold_B:
    mode: trunk
    vlans: "210-211"
  PC1:
    mode: access
    vlans: "34"
  PC2:
    mode: access
    vlans: "12"

servers:
  host01:
    rack: rack01
    adapters:
      - endpoint_ports: [Eth1, Eth2]
        switch_ports: [Ethernet19, Ethernet20]
        switches: [Leaf1, Leaf2]
        profile: Hosts1
        port_channel:
          description: PortChannel to Host1
          mode: active
          
  host02:
    rack: rack01
    adapters:
      - endpoint_ports: [Eth1, Eth2]
        switch_ports: [Ethernet19, Ethernet20]
        switches: [Leaf3, Leaf4]
        profile: Hosts2
        port_channel:
          mode: active
          description: PortChannel to Host2
        ethernet_segment:
          short_esi: 0101:0102:0044
          redundancy: all-active
  # Adding these test single homed hosts so they dont get removed each time avd is deployed.        
  PC-1:
    rack: rack01
    adapters:
      - endpoint_ports: [Eth1]
        switch_ports: [Ethernet10]
        switches: [Leaf4]
        profile: PC1

  PC-2:
    rack: rack01
    adapters:
      - endpoint_ports: [Eth1]
        switch_ports: [Ethernet15]
        switches: [Leaf1]
        profile: PC2