---
# Endpoint connectivity in the online Docs

port_profiles:
  Old_Gold_A_B:
    mode: trunk
    vlans: "12,210-211"
  Old_Gold_A:
    mode: trunk
    vlans: "12,110,160"
  Old_Gold_B:
    mode: trunk
    vlans: "210-211"

servers:
  host1:
    rack: rack01
    adapters:
      - endpoint_ports: [Eth1, Eth2]
        switch_ports: [Ethernet19, Ethernet20]
        switches: [Leaf1, Leaf2]
        profile: Old_Gold_A
        port_channel:
          description: PortChannel3
          mode: active
          
  host2:
    rack: rack01
    adapters:
      - endpoint_ports: [Eth1, Eth2]
        switch_ports: [Ethernet19, Ethernet20]
        switches: [Leaf3, Leaf4]
        profile: Old_Gold_A
        ethernet_segment:
          short_esi: 0101:0102:0044
          redundancy: all-active