---
port_profiles:
  TENANT_A_B:
    mode: trunk
    vlans: "12,210-211"
  TENANT_A:
    mode: access
    vlans: "12"
  TENANT_B:
    mode: trunk
    vlans: "210-211"

servers:
  server01:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [Eth0]
        switch_ports: [Ethernet4]
        switches: [DC1-LEAF1A]
        profile: TENANT_A
  server02:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [Eth0]
        switch_ports: [Ethernet4]
        switches: [DC1-LEAF2A]
        profile: TENANT_A
